const score = document.querySelector(".game_score");
const myChoice = document.querySelector(".paper-img");
const computerChoice = document.querySelector(".scissors-img");
const rockImg = document.querySelector(".rock-img");
const paper = document.querySelector(".paper-gradient");
const scissors = document.querySelector(".scissors-gradient");
const rock = document.querySelector(".rock-gradient");
const section = document.querySelector(".section");
const images = document.querySelectorAll(".img");
const popup = document.querySelector(".popup");
const rulesButton = document.querySelector(".rules");
const closeRules = document.querySelector(".closed");
const modal = document.querySelector(".modal");
const choiceParagraph = document.querySelector(".choiceEasy");
const houseParagraph = document.querySelector(".houseEasy");
const statusEasy = document.querySelector(".statusEasy");
const statusModeEasy = document.querySelector(".statusModeEasy");
const playAgainEasy = document.querySelector(".playAgainEasyButton");
const playAgain = document.querySelector(".playAgainEasyButton");
const circle = document.querySelector(".circle");
const level = document.querySelector(".levelMode");
const easyMode = document.querySelector(".easyMode");
const hardMode = document.querySelector(".hardMode");
const rulesImage = document.querySelector(".rulesImage");
const logo =  document.querySelector(".logo")
const desktopDisplay = document.querySelector('.paper_scissors')


// Hard
const lizardImgHard = document.querySelector(".lizard-img-hard");
const computerChoiceHard = document.querySelector(".paper-img-hard");
const spockHard = document.querySelector(".spock-gradient-hard");
const scissorsHard = document.querySelector(".scissors-gradient-hard");
const rockHard = document.querySelector(".rock-gradient-hard");
const paperHard= document.querySelector(".paper-gradient-hard");
const statusHard = document.querySelector(".statusHard");
const statusModeHard = document.querySelector(".statusModeHard");
const lizardHard = document.querySelector(".lizard-gradient-hard");
const myChoiceHard = document.querySelector(".spock-img-hard");
const rockImgHard = document.querySelector(".rock-img-hard");
const scissorsImgHard = document.querySelector(".scissors-img-hard");
const imagesHard = document.querySelectorAll(".img-hard");
const sectionHard = document.querySelector(".section-hard");
const popupHard = document.querySelector(".popupHard");
const choiceParagraphHard = document.querySelector(".choiceHard");
const houseParagraphHard = document.querySelector(".houseHard");
const playAgainHard = document.querySelector(".playAgainHardButton");
const desktopDisplayHard = document.querySelector('.spock-paper')